### PR TITLE
Add 2016 recordings

### LINKED ISSUE #68: Add 2016 recordings page
The recordings are up on YouTube: https://www.youtube.com/playlist?list=PLz7lZ05Uowln1w5-nh0vcPI4NUC_kMJsE

Add them to the 2016 recordings page, and add a link to it to the 2016 page!

### PR DESCRIPTION
**Pull request by jasonaowen**
Update the 2016 recordings page to show the videos in the YouTube playlist!

After looking through the 2014 and 2015 recordings pages, they seem to have some very similar (but not identical) JavaScript. So, here's my plan:

- [x] extract 2014 talks into a JSON file, and use AJAX to load it
- [x] extract 2015 talks into a JSON file, and use AJAX to load it
- [x] refactor to extract common JavaScript into a shared file, used by both 2014 and 2015
- [x] put 2016 talks into a JSON file
- [x] update the 2016 recordings page to include the shared script and the 2016 data

Resolves #68 add 2016 recordings page

### CODE REVIEW

**Comment by lkuper** [comment]
Maybe @ertyseidohl will have more feedback, but this approach sounds reasonable to me!  I say carry on. :+1:

**Comment by jasonaowen** [comment]
Okay, refactoring done! Tomorrow I'll add the 2016 data.

**Comment by jasonaowen** [comment]
@lkuper @ertyseidohl I think this is ready to merge! It got... kinda big, but I tried to keep the individual commits easily reviewable.

**Comment by jasonaowen** [comment]
I have it up on my fork, if you want to see the end result: https://jasonaowen.github.io/bangbangcon.github.io/2016/ . The only change in that branch that's not in this PR is deleting the `CNAME` file.

To test, I checked that I could see the embedded video for each talk, and that the link from the speaker to the speakers page worked correctly. Thank you for making sure all the talks in the program are present and in order in the YouTube playlist - that made it much easier for me to double-check that I'd gotten all the talks!

**Comment by ertyseidohl** [comment]
:+1:

**Comment by ertyseidohl** [comment]
I'll go ahead and merge if nobody has any objections

**Comment by lkuper** [comment]
Looks good to me too!  Thanks @jasonaowen.

**Comment by lkuper** [comment]
@ertyseidohl are you going to merge this?

**Comment by ertyseidohl** [comment]
Whoops - didn't get a notif! Sorry @lkuper @jasonaowen -- merging.

**Pull request merged**
